### ISSUE TITLE
UnsignedInteger is causing a SerialVersionID issue in Spark

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#158] opened 2015-02-03 16:44 UTC
I'm not sure why yet. I just updated mango and to my knowledge, I'm not even using the unsigned integer anywhere. Spark has a different version of Guava, however. For now, I've downgraded the version mango is using to 14.0.1 (spark's version) to see if that would fix and it does not appear to have helped.

**Comment by eawagner** [comment] 2015-02-03 19:16
Can you paste the error message?  Is this when trying to serialize the TypeRegisty?

**Comment by cjnolet** [comment] 2015-02-03 20:44
I can't paste the error message unfortunately :-/

My solutino for now is to make my own type registry which does not include
the Guava types. not sure why this is an issue, I've verified that this
version of Guava is the only one on the classpath... but for now, I have no
other choice.

Spark and Akka have a unique way of shipping code off to be executed
remotely using a class called the "Closure Cleaner". It's job is to try to
prune what it can out of the classes surrounding a closure to minimize the
amount of the object tree that needs to be shipped. Unfortunately, since I
have an instance of  aclass surrounding the closure that' sbeing shipped,
the type registry is being shipped too- which worked on the last version of
Mango (I updated last night to the current version).

**Comment by eawagner** [comment] 2015-02-03 22:50
Interesting.  I don't know how much of an issue the version of Guava would be since UnsignedInteger class has been around since guava 11.0.  I have also tested the serialization/deserialization does work without error (going to add this test to the unit tests).

Would be interested in what is causing this problem in a Spark environment.

**Comment by cjnolet** [comment] 2015-02-03 23:30
Its complaining about the serial version id

**Comment by cjnolet** [comment] 2015-02-04 01:05
Unfortunately, I was not able to dive in far enoiught o see exactly which class was being picked up on the classpath but the error was very clear- there was an unexpected version of the UnsignedInteger class on the classpath. I did verify in maven itself that there was only 1 version of Guava- I tried both the old version that SPark uses and the newer version that both Mango & Jackson are using.

I'm beginning to wonder if either there's a dependency that has copied a bunch of the guava classes into its own jar, or a more likely case, Spark is including something installed on the system (like Hadoop) into its classpath which has a varying version of that class. I'll try to investigate more tomorrow- it's a pretty big issue for me right now as I'm getting the Calrissian Event Store deployed out

**Comment by eawagner** [comment] 2015-02-04 03:46
I was able to reproduce this issue with an old version of guava.  I tried all versions of guava and have found that the generated serialVersionUID for UnsignedInteger changed between 14.0.1 and 15.0 and previously between earlier versions (testing back to 11.0.2).

This actually led me down a path to check compatability of a few things with mango 1.3.0.
Guava compatability:
* >= 15.0 -> fully compatable
* 14.0.1 -> All works except EntityRelationshipEncoder, also serialization id of Unsigned{Int,Long} changed, and possibly others.
* <= 13.0.1 -> Does not compile (but should be runtime compatible if you avoid the offending classes.)

Mango serialization compatability between 1.3.0 and older versions (for older persisted data objects or when deserializing with an older version of mango on the classpath).
* TypeRegistry is not compatable
* Event/Entity/BaseTupleStore are not compatable
* Basically anything that does not define a serialVersionUID which I stopped testing after I found these.

I think for a start, we should be defining the serializationVersionUID for all our classes, as any change in the class seems to generate a new one.

If you just want to fix the serialization issue, I think your work around is the right way to go.  Use a custom TypeRegistry with the encoders that work for you.  If the point is to be backward compatable with earlier versions of Guava, then we need to pick a version and compile and test against that.  If the point is to remain serialization compatable, then we have already failed with our own classes and I would like to address that issue holistically as I believe that is a bug.

Im a little conflicted on how to handle the support for older guava dependencies, however.  On the one hand, I would like to be fully forward and backward compatable with various versions of guava.  For instance, I have been careful to avoid using deprecated methods/classes for newer versions of guava to allow for better compatabiliy going forward, but a lot of mango is just not backwards compatable with Guava earlier than 14.0.1 due to the use of API's that guava has made available since 13.0.1.  

Sorry, for the long winded response, but trying to duplicated this behaviour led me down a rabbit hole that got me started with compatability issues.

**Comment by cjnolet** [comment] 2015-02-19 13:29
Just an update- I was able to shade the guava packages in my main jars and it looks like it worked fine. I'm okay pushing this off until 1.5.x (we probably shouldn't add it in 1.4.x if we're following semver).

**Comment by eawagner** [comment] 2015-02-19 14:10
What would we be pushing off.  I know I did a lot of investigation, but I don't know of any agreed upon resolution to this issue.

The only thing I know of that would help address this issue is #160 to help build a custom registry starting from only the Java types which are fully compatible across all the tested guava versions.

Offline I know we had also talked about avoiding Splitter for performance reasons which would help with 14.0.1 compatability, but won't change the serialVersionUID issue unless we actually downgraded out guava dependency to 14.0.1.

**Comment by cjnolet** [comment] 2015-02-19 14:13
#160 is what I'm referring to.

**Comment by eawagner** [comment] 2015-02-19 14:36
I got ya.  Considering it would just be an additional constant, I think inclusion into 1.4.0 would be ok and not need to be pushed to 1.5.x following semver.  I don't want to deprecate the old constant, just provide an alternative for those who just wanted the basic java types.  Deprecation is still on the table, but I would table that to a 2.x release.

I suggest we mark this a "won't fix" for now.  We can pick up the #160 discussion in that thread if there are any other concerns.

**Comment by cjnolet** [comment] 2015-02-19 15:37
Sounds good to me.

**Closed** 2015-03-15 09:02 UTC
Labels: wontfix
